### ISSUE TITLE
When running the install, it says that Flask is missing

### ISSUE THREAD

**Issue by gelnior** [guyzmo/clait#2]
Hello there,

When I run a `python setup.py install` it says that `Flask distribution` is not present. It results in an error and the build fails.

After installing Flask through `pip`, everything runs well.

Env : Python 3.5.2

**Comment by guyzmo** [comment]
well, one shouldn't install a package using `setup.py install` in 2017, pip is a better way to go. The issue is that the install command doesn't know how to resolve dependencies, whereas pip does.

**Comment by gelnior** [comment]
In that case, the README is wrong. It says to install clait through the install command.
